project:
  type: website
  title: "MCI_SBT_B_1_GID_2"
  output-dir: _site
  resources:
    - docs/iot-specs/asyncapi.yaml
    - docs/iot-specs/openapi.yaml
    - docs/iot-specs/conventions.md
    - src/raspi_firmware/settings.toml
    - src/raspi_firmware/code.py


website:
  title: "Industrial IoT"
  reader-mode: true
  page-footer:
    left: Industrial IoT 1 WiSe 2025 (MECH-M-4-IIoT)
    center: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) Julian Huber"
    right: This book was built with <a href="https://quarto.org/">Quarto</a>.
  navbar:
    left:
      - href: docs/Dokumentation.qmd
        text: Eigene Dokumentation

format:
  html:
    theme: cosmo
    toc: true