services:
  influxdb2:
    container_name: ${INFLUXDB_HOST}
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_INIT_ADMIN_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
    volumes:
      - ./src/cloud/influx/data:/var/lib/influxdb2
      - ./src/cloud/influx/config:/etc/influxdb2

  telegraf:
    container_name: telegraf
    image: telegraf:1.30
    depends_on:
      - ${INFLUXDB_HOST}
    environment:
      INFLUXDB_HOST: ${INFLUXDB_HOST}
      INFLUXDB_TOKEN: ${INFLUXDB_INIT_ADMIN_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      TELEGRAF_COLLECTION_INTERVAL: ${TELEGRAF_COLLECTION_INTERVAL}
      HOSTNAME: telegraf
      MQTT_IP_ADDRESS: ${MQTT_IP_ADDRESS}
      MQTT_NAME: ${MQTT_NAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    volumes:
      - ./src/cloud/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    container_name: grafana
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    volumes:
      - ./src/cloud/grafana/data:/var/lib/grafana
      - ./src/cloud/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/sensor_overview.json
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - ${INFLUXDB_HOST}
    
volumes:
  influxdb2-data:
  influxdb2-config:
  grafana_data:
