[agent]
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  hostname = "telegraf"

###############################################################################
# MQTT INPUT (from Raspberry Pico W)
###############################################################################
[[inputs.mqtt_consumer]]
  servers = ["tcp://${MQTT_IP_ADDRESS}:1883"]
  topics = [
    "iiot/group/+/sensor/temperature",
    "iiot/group/+/sensor/humidity",
    "iiot/group/+/sensor/status",
  ]
  username = "${MQTT_NAME}"
  password = "${MQTT_PASSWORD}"

  qos = 0
  connection_timeout = "30s"
  persistent_session = false
  client_id = "telegraf-mqtt"

  tag_keys = ["sensor_id"]
  json_string_fields = ["status"]
  data_format = "json"

###############################################################################
# OUTPUT: InfluxDB v2
###############################################################################
[[outputs.influxdb_v2]]
  urls = ["http://${INFLUXDB_HOST}:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
