[agent]
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  hostname = "telegraf"

###############################################################################
# MQTT INPUT (from Raspberry Pico W)
###############################################################################
[[inputs.mqtt_consumer]]
  servers = ["tcp://${MQTT_IP_ADDRESS}:1883"]
  topics = [
    "iiot/group/+/sensor/temperature",
    "iiot/group/+/sensor/humidity",
    "iiot/group/+/sensor/status",
  ]
  username = "${MQTT_NAME}"
  password = "${MQTT_PASSWORD}"

  qos = 0
  connection_timeout = "30s"
  persistent_session = false
  client_id = "telegraf-mqtt"
  

  # [[inputs.mqtt_consumer.topic_parsing]]
  #   topic = "iiot/group/_/_/_"
  #   measurement = "_/_/measurement/_/_"
  #   fields = "_/_/_/_/field"
  #   [inputs.mqtt_consumer.topic_parsing.types]
  #     field = "string"

  # #  [[inputs.mqtt_consumer.topic_parsing]]
  # # topic = "iiot/group/([^/]+)/sensor/([^/]+)"
  # #   measurement = "$1"  # group name becomes measurement
  # #   tags = { sensor_id="$2" }  # temperature/humidity/status as tag if needed
  # data_format = "json_v2"

  # [[inputs.mqtt_consumer.json_v2]]
  #   [[inputs.mqtt_consumer.json_v2.value]]
  #       path = "value"
  #       type = "int"
  # #   [[inputs.mqtt_consumer.json_v2.field]]
  # #       path = "longitude"
  # #       rename = "lon"
  # #       type = "float"
  
###############################################################################
# OUTPUT: InfluxDB v2
###############################################################################
[[outputs.influxdb_v2]]
  urls = ["http://${INFLUXDB_HOST}:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
