[agent]
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  hostname = "telegraf"

###############################################################################
# MQTT INPUT (from Raspberry Pico W)
###############################################################################
[[inputs.mqtt_consumer]]
  servers = ["tcp://${MQTT_IP_ADDRESS}:1883"]
  topics = [
    "iiot/group/+/sensor/temperature",
    "iiot/group/+/sensor/humidity",
  ]
  username = "${MQTT_NAME}"
  password = "${MQTT_PASSWORD}"

  qos = 0
  connection_timeout = "30s"
  persistent_session = false
  client_id = "telegraf-mqtt"
  
  data_format = "json"
  tag_keys = ["sensor_id"]
  json_string_fields = ["unit", "status"]

##### test
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.mem]]

[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.system]]
  
###############################################################################
# OUTPUT: InfluxDB v2
###############################################################################
[[outputs.influxdb_v2]]
  urls = ["http://${INFLUXDB_HOST}:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
