[agent]
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  hostname = "telegraf"

###############################################################################
# MQTT INPUT (AWS IoT Core)
###############################################################################
[[inputs.mqtt_consumer]]
  ## AWS IoT Core Endpunkt (findest du in der AWS Konsole unter 'Settings')
  servers = ["ssl://${AWS_IOT_ENDPOINT}:8883"]
  
  topics = [
    "iiot/group/+/sensor/temperature",
    "iiot/group/+/sensor/humidity",
    "iiot/group/+/sensor/status",
  ]

  qos = 1 # AWS empfiehlt oft QoS 1
  connection_timeout = "30s"
  client_id = "telegraf-client-01" # Muss in AWS registriert/erlaubt sein

  ## TLS Zertifikate
  # tls_ca = "/etc/telegraf/certs/AmazonRootCA1.pem"
  # tls_cert = "/etc/telegraf/certs/3d2524c24370152244278903340ef4ed600ef1d2636d642db56cdba0ba860da7-certificate.pem.crt"
  # tls_key = "/etc/telegraf/certs/3d2524c24370152244278903340ef4ed600ef1d2636d642db56cdba0ba860da7-private.pem.key"
  tls_ca = "$TLS_CA_PATH"
  tls_cert = "$TLS_CERT_PATH"
  tls_key = "$TLS_KEY_PATH"

  tag_keys = ["sensor_id"]
  json_string_fields = ["status"]
  data_format = "json"

###############################################################################
# OUTPUT: InfluxDB v2
###############################################################################
[[outputs.influxdb_v2]]
  urls = ["http://${INFLUXDB_HOST}:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"