{
 "title": "Sensor Overview Dashboard",
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sensor_id",
    "label": "Sensor",
    "query": "import \"influxdata/influxdb/schema\"\n schema.tagValues(bucket: \"sensor_data\", tag: \"sensor_id\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Degiampietro-Kern Humidity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"iiot/group/degiampietro-kern/sensor/humidity\")\n\n"
    }
   ]
  },
  {
   "title": "Degiampietro-Kern Temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"iiot/group/degiampietro-kern/sensor/temperature\")\n\n"
    }
   ]
  },
  {
   "title": "Available Sensors Measurements",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: -1h)\r\n  |> distinct(column: \"topic\")\r\n  |> keep(columns: [\"topic\"])\r\n  |> group(columns: [])\r\n  |> filter(fn: (r) => r.topic !~ /status/)"
    }
   ]
  },
  {
   "title": "All Temperature graphs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: -2h)\r\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.topic =~ /sensor\\/temperature$/) "
    }
   ]
  },
  {
   "title": "All Humidity graphs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: -2h)\r\r\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.topic =~ /sensor\\/humidity$/) "
    }
   ]
  },
  {
   "title": "Last Status of Sensors",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> group(columns: [\"topic\"])\r\n  |> last()\r\n  |> group()  \r\n  |> keep(columns: [\"_value\", \"topic\"])\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n"
    }
   ]
  }
 ]
}